# Environment setup needed to make mLua search for vendored Lua instead using Lua-sys which has no target for the 3ds
[env]
LUA_LIB = { value = "vendor/lua/lua-5.4.9/src", relative = true }
LUA_LIB_NAME = "lua"
LUA_LINK = "static"
